#!/bin/sh
#
# freesentral-db:	Initializes the database for FreeSentral service
#
# chkconfig: 345 90 10
# description: Creates the PostgreSQL database used by the FreeSentral service
#

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

init() {
    echo -n $"Creating FreeSentral Database: "
    /usr/libexec/freesentral/install.sh --quiet --config no --scripts no --prompts no --webpage no
    case "X$RETVAL" in
	X0)
	    success
	    ;;
	X1)
	    passed
	    ;;
	*)
	    failure
	    RETVAL=1
	    ;;
    esac
    echo
}

# See how we were called.
case "$1" in
    init)
	init
	;;
    start)
	init
	chkconfig freesentral-db off
	;;
    stop)
	;;
    *)
	echo $"Usage: $0 {init|start}"
	;;
esac
exit $RETVAL
