#!/bin/sh
#
# freesentral-init:	Initializes the system for FreeSentral service
#
# chkconfig: 345 90 10
# description: Initializes a system used as FreeSentral service
#

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

init() {
    echo -n $"Initializing FreeSentral: "
    # database
    /usr/libexec/freesentral/install.sh --no_defaults --quiet
    # system
    /usr/libexec/freesentral/install.sh init_system
    # certificates
    DESTDIR=/etc/freesentral /usr/libexec/freesentral/install.sh --no_defaults generate_certificate
    case "X$?" in
	X0)
	    success
	    ;;
	X1)
	    passed
	    ;;
	*)
	    failure
	    RETVAL=1
	    ;;
    esac
    echo
}

# See how we were called.
case "$1" in
    init)
	init
	;;
    start)
	init
	chkconfig freesentral-init off
	;;
    stop)
	;;
    *)
	echo $"Usage: $0 {init|start}"
	;;
esac
exit $RETVAL
